In [39]:
#import librairies
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [89]:
books=pd.read_csv('bestsellers with categories.csv')

In [76]:
books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [42]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


In [43]:
books.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [90]:
#getting unique rows/Title
books=books.drop_duplicates(subset=['Name'], ignore_index=True)

In [91]:
books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
346  Winter of the World: Book Two of the Century T...   
347  Women Food and God: An Unexpected Path to Almo...   
348                                             Wonder   
349       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
350  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
346               Ken Follett          4.5    10760     15  2012      Fiction  
347               Geneen Roth          4.2     1302     11  2010  Non Fiction  
348             R. J. Palacio          4.8    21625      9  2013      Fiction  
349               Jeff Kinney          4.9     9413      8  2019      Fiction  
350               Jen Sincero          4.7    14331      8  2016  Non Fiction  

[351 rows x 7 columns]

In [94]:
books.reset_index(inplace=True)
books = books.rename(columns = {'index':'book_id'})

In [95]:
books

book_id                                               Name  \
0          0                      10-Day Green Smoothie Cleanse   
1          1                                  11/22/63: A Novel   
2          2            12 Rules for Life: An Antidote to Chaos   
3          3                             1984 (Signet Classics)   
4          4  5,000 Awesome Facts (About Everything!) (Natio...   
..       ...                                                ...   
346      346  Winter of the World: Book Two of the Century T...   
347      347  Women Food and God: An Unexpected Path to Almo...   
348      348                                             Wonder   
349      349       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
350      350  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
346               Ken Follett          4.5    10760     15  2012      Fiction  
347               Geneen Roth          4.2     1302     11  2010  Non Fiction  
348             R. J. Palacio          4.8    21625      9  2013      Fiction  
349               Jeff Kinney          4.9     9413      8  2019      Fiction  
350               Jen Sincero          4.7    14331      8  2016  Non Fiction  

[351 rows x 8 columns]

In [96]:
columns=['Name','Author', 'Genre','Reviews']

In [97]:
def combine_features(data):
    features=[]
    for i in range(0, data.shape[0]):
        features.append(data['Name'][i]+' '+data['Author'][i]+' '+data['Genre'][i])
    return features

In [98]:
books['combined_features']=combine_features(books)

In [99]:
books

book_id                                               Name  \
0          0                      10-Day Green Smoothie Cleanse   
1          1                                  11/22/63: A Novel   
2          2            12 Rules for Life: An Antidote to Chaos   
3          3                             1984 (Signet Classics)   
4          4  5,000 Awesome Facts (About Everything!) (Natio...   
..       ...                                                ...   
346      346  Winter of the World: Book Two of the Century T...   
347      347  Women Food and God: An Unexpected Path to Almo...   
348      348                                             Wonder   
349      349       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
350      350  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
346               Ken Follett          4.5    10760     15  2012      Fiction   
347               Geneen Roth          4.2     1302     11  2010  Non Fiction   
348             R. J. Palacio          4.8    21625      9  2013      Fiction   
349               Jeff Kinney          4.9     9413      8  2019      Fiction   
350               Jen Sincero          4.7    14331      8  2016  Non Fiction   

                                     combined_features  
0    10-Day Green Smoothie Cleanse JJ Smith Non Fic...  
1               11/22/63: A Novel Stephen King Fiction  
2    12 Rules for Life: An Antidote to Chaos Jordan...  
3         1984 (Signet Classics) George Orwell Fiction  
4    5,000 Awesome Facts (About Everything!) (Natio...  
..                                                 ...  
346  Winter of the World: Book Two of the Century T...  
347  Women Food and God: An Unexpected Path to Almo...  
348                       Wonder R. J. Palacio Fiction  
349  Wrecking Ball (Diary of a Wimpy Kid Book 14) J...  
350  You Are a Badass: How to Stop Doubting Your Gr...  

[351 rows x 9 columns]

In [100]:
#Convert the text from the nex column to a matrix word counts
cm = CountVectorizer().fit_transform(books['combined_features'])

In [101]:
cs = cosine_similarity(cm)

In [102]:
print(cs)

[[1.         0.12598816 0.19245009 ... 0.19245009 0.10050378 0.15294382]
 [0.12598816 1.         0.10910895 ... 0.21821789 0.11396058 0.086711  ]
 [0.19245009 0.10910895 1.         ... 0.16666667 0.08703883 0.33113309]
 ...
 [0.19245009 0.21821789 0.16666667 ... 1.         0.17407766 0.13245324]
 [0.10050378 0.11396058 0.08703883 ... 0.17407766 1.         0.06917145]
 [0.15294382 0.086711   0.33113309 ... 0.13245324 0.06917145 1.        ]]


In [103]:
#Get the title of the book the reader likes
title = books['Name'][1]
title

'11/22/63: A Novel'

In [ ]:
#book written by Stephen King

In [104]:
book_id = books[books.Name == title]['book_id'].values[0]

In [105]:
book_id

1

In [106]:
scores = list(enumerate(cs[book_id]))

In [118]:
print(scores)

In [108]:
sorted_scores = sorted(scores, key= lambda x:x[1], reverse=True)

In [109]:
sorted_scores = sorted_scores[1:]

In [117]:
sorted_scores

In [111]:
# create a loop to print the first 5 books from the sorted list
j=0
print('The five most recommended books to '+title+' are:\n')
for item in sorted_scores:
    book_title = books[books.book_id == item[0]]['Name'].values[0]
    print (j+1, book_title)
    j=j+1
    if j >= 5:
        break

The five most recommended books to 11/22/63: A Novel are:

1 Doctor Sleep: A Novel
2 Under the Dome: A Novel
3 Joyland (Hard Case Crime)
4 The Goldfinch: A Novel (Pulitzer Prize for Fiction)
5 Little Bee: A Novel
