In [39]:
#import librairies
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [143]:
books=pd.read_csv('bestsellers with categories.csv')

In [76]:
books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [42]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


In [43]:
books.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [144]:
#getting unique rows/Title
books=books.drop_duplicates(subset=['Name'], ignore_index=True)

In [145]:
books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
346  Winter of the World: Book Two of the Century T...   
347  Women Food and God: An Unexpected Path to Almo...   
348                                             Wonder   
349       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
350  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
346               Ken Follett          4.5    10760     15  2012      Fiction  
347               Geneen Roth          4.2     1302     11  2010  Non Fiction  
348             R. J. Palacio          4.8    21625      9  2013      Fiction  
349               Jeff Kinney          4.9     9413      8  2019      Fiction  
350               Jen Sincero          4.7    14331      8  2016  Non Fiction  

[351 rows x 7 columns]

In [146]:
books=books.sort_values(by=['User Rating'], ascending=False, ignore_index=True)

In [147]:
books

Name              Author  \
0                             Hamilton: The Revolution  Lin-Manuel Miranda   
1    Rush Revere and the First Patriots: Time-Trave...       Rush Limbaugh   
2    Harry Potter and the Sorcerer's Stone: The Ill...        J.K. Rowling   
3    Harry Potter and the Prisoner of Azkaban: The ...        J.K. Rowling   
4    Harry Potter and the Goblet of Fire: The Illus...       J. K. Rowling   
..                                                 ...                 ...   
346  The Goldfinch: A Novel (Pulitzer Prize for Fic...         Donna Tartt   
347                                          Allegiant       Veronica Roth   
348  Fifty Shades of Grey: Book One of the Fifty Sh...           E L James   
349                         Go Set a Watchman: A Novel          Harper Lee   
350                                 The Casual Vacancy        J.K. Rowling   

     User Rating  Reviews  Price  Year        Genre  
0            4.9     5867     54  2016  Non Fiction  
1            4.9     3836     12  2014      Fiction  
2            4.9    10052     22  2016      Fiction  
3            4.9     3146     30  2017      Fiction  
4            4.9     7758     18  2019      Fiction  
..           ...      ...    ...   ...          ...  
346          3.9    33844     20  2013      Fiction  
347          3.9     6310     13  2013      Fiction  
348          3.8    47265     14  2012      Fiction  
349          3.6    14982     19  2015      Fiction  
350          3.3     9372     12  2012      Fiction  

[351 rows x 7 columns]

In [148]:
books.reset_index(inplace=True)
books = books.rename(columns = {'index':'book_id'})

In [149]:
books

book_id                                               Name  \
0          0                           Hamilton: The Revolution   
1          1  Rush Revere and the First Patriots: Time-Trave...   
2          2  Harry Potter and the Sorcerer's Stone: The Ill...   
3          3  Harry Potter and the Prisoner of Azkaban: The ...   
4          4  Harry Potter and the Goblet of Fire: The Illus...   
..       ...                                                ...   
346      346  The Goldfinch: A Novel (Pulitzer Prize for Fic...   
347      347                                          Allegiant   
348      348  Fifty Shades of Grey: Book One of the Fifty Sh...   
349      349                         Go Set a Watchman: A Novel   
350      350                                 The Casual Vacancy   

                 Author  User Rating  Reviews  Price  Year        Genre  
0    Lin-Manuel Miranda          4.9     5867     54  2016  Non Fiction  
1         Rush Limbaugh          4.9     3836     12  2014      Fiction  
2          J.K. Rowling          4.9    10052     22  2016      Fiction  
3          J.K. Rowling          4.9     3146     30  2017      Fiction  
4         J. K. Rowling          4.9     7758     18  2019      Fiction  
..                  ...          ...      ...    ...   ...          ...  
346         Donna Tartt          3.9    33844     20  2013      Fiction  
347       Veronica Roth          3.9     6310     13  2013      Fiction  
348           E L James          3.8    47265     14  2012      Fiction  
349          Harper Lee          3.6    14982     19  2015      Fiction  
350        J.K. Rowling          3.3     9372     12  2012      Fiction  

[351 rows x 8 columns]

In [165]:
columns=['Name','Author', 'Genre']

In [166]:
def combine_features(data):
    features=[]
    for i in range(0, data.shape[0]):
        features.append(data['Name'][i]+' '+data['Author'][i]+' '+data['Genre'][i])
    return features

In [167]:
books['combined_features']=combine_features(books)

In [168]:
#Convert the text from the next column to a matrix word counts
cm = CountVectorizer().fit_transform(books['combined_features'])

In [169]:
cs = cosine_similarity(cm)

In [170]:
print(cs)

[[1.         0.17149859 0.23717082 ... 0.11470787 0.13363062 0.31622777]
 [0.17149859 1.         0.21693046 ... 0.07868895 0.09166985 0.21693046]
 [0.23717082 0.21693046 1.         ... 0.14509525 0.08451543 0.4       ]
 ...
 [0.11470787 0.07868895 0.14509525 ... 1.         0.06131393 0.14509525]
 [0.13363062 0.09166985 0.08451543 ... 0.06131393 1.         0.16903085]
 [0.31622777 0.21693046 0.4        ... 0.14509525 0.16903085 1.        ]]


In [171]:
#Get the title of the book the reader likes
title = books['Name'][1]
title

'Rush Revere and the First Patriots: Time-Travel Adventures With Exceptional Americans (2)'

In [172]:
book_id = books[books.Name == title]['book_id'].values[0]

In [173]:
book_id

1

In [174]:
scores = list(enumerate(cs[book_id]))

In [175]:
print(scores)

[(0, 0.17149858514250882), (1, 1.0), (2, 0.21693045781865616), (3, 0.21170244960998527), (4, 0.21170244960998527), (5, 0.21170244960998527), (6, 0.1455213750217998), (7, 0.06063390625908324), (8, 0.8823529411764707), (9, 0.05170876899950191), (10, 0.1533929977694741), (11, 0.0700140042014005), (12, 0.18333969940564224), (13, 0.16169041669088863), (14, 0.1455213750217998), (15, 0.14852213144650117), (16, 0.11128297681493143), (17, 0.16269784336399212), (18, 0.18333969940564224), (19, 0.10114434748483472), (20, 0.12964074471043288), (21, 0.07312724241271307), (22, 0.08084520834544431), (23, 0.140028008402801), (24, 0.09901475429766744), (25, 0.16169041669088863), (26, 0.17149858514250882), (27, 0.08574929257125441), (28, 0.09901475429766744), (29, 0.17149858514250882), (30, 0.1764705882352941), (31, 0.22917462425705282), (32, 0.07312724241271307), (33, 0.27500954910846337), (34, 0.27022640946662696), (35, 0.21693045781865616), (36, 0.08574929257125441), (37, 0.23008949665421113), (38, 0.

In [176]:
sorted_scores = sorted(scores, key= lambda x:x[1], reverse=True)

In [177]:
sorted_scores = sorted_scores[1:]

In [178]:
sorted_scores

[(8, 0.8823529411764707),
 (305, 0.28539089649269644),
 (33, 0.27500954910846337),
 (288, 0.27500954910846337),
 (328, 0.27500954910846337),
 (34, 0.27022640946662696),
 (294, 0.269069117598525),
 (98, 0.25928148942086576),
 (221, 0.25724787771376323),
 (138, 0.24253562503633294),
 (302, 0.23529411764705882),
 (190, 0.2333800140046683),
 (37, 0.23008949665421113),
 (109, 0.23008949665421113),
 (158, 0.23008949665421113),
 (191, 0.23008949665421113),
 (244, 0.23008949665421113),
 (259, 0.23008949665421113),
 (340, 0.23008949665421113),
 (343, 0.23008949665421113),
 (31, 0.22917462425705282),
 (142, 0.22518867455552247),
 (206, 0.22256595362986287),
 (300, 0.22140372138502382),
 (112, 0.2193817272381392),
 (283, 0.2193817272381392),
 (2, 0.21693045781865616),
 (35, 0.21693045781865616),
 (38, 0.21693045781865616),
 (41, 0.21693045781865616),
 (130, 0.21693045781865616),
 (135, 0.21693045781865616),
 (297, 0.21693045781865616),
 (313, 0.21693045781865616),
 (350, 0.21693045781865616),
 (3

In [179]:
# create a loop to print the first 5 books from the sorted list
j=0
print('The five most recommended books to '+title+' are:\n')
for item in sorted_scores:
    book_title = books[books.book_id == item[0]]['Name'].values[0]
    print (j+1, book_title)
    j=j+1
    if j >= 5:
        break

The five most recommended books to Rush Revere and the First Patriots: Time-Travel Adventures With Exceptional Americans (2) are:

1 Rush Revere and the Brave Pilgrims: Time-Travel Adventures with Exceptional Americans (1)
2 Game Change: Obama and the Clintons, McCain and Palin, and the Race of a Lifetime
3 The Book with No Pictures
4 The Time Traveler's Wife
5 And the Mountains Echoed
